--- #YAML:1.0
name:                     CPAN-Testers-Data-Generator
version:                  1.03
abstract:                 CPAN Testers cpanstats Database Generator
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                               5.006
  Config::IniFiles:                   0
  CPAN::Testers::Common::Article:     0.36
  CPAN::Testers::Common::DBUtils:     0.03
  CPAN::Testers::Fact::LegacyReport:  0
  CPAN::Testers::Fact::TestSummary:   0
  CPAN::Testers::Metabase::AWS:       0
  CPAN::Testers::Report:              0
  DBI:                                0
  DBD::mysql:                         0
  DBD::SQLite:                        1.07
  File::Basename:                     0
  File::Path:                         0
  File::Slurp:                        0
  Getopt::ArgvFile:                   0
  Getopt::Long:                       0
  HTML::Entities:                     0
  IO::File:                           0
  JSON:                               0
  Metabase:                           0.014
  Metabase::Fact:                     0
  Time::Local:                        0
  XML::Feed:                          0
recommends:
  Test::CPAN::Meta:                   0
  Test::CPAN::Meta::JSON:             0
  Test::Pod:                          1.00
  Test::Pod::Coverage:                0.08
build_requires:
  Test::More:                         0.70

provides:
  CPAN::Testers::Data::Generator:
    file:     lib/CPAN/Testers/Data/Generator.pm
    version:  1.03

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Data-Generator
  repository: http://github.com/barbie/cpan-testers-data-generator.git

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
