--- #YAML:1.0
name:                     CPAN-Testers-Data-Generator
version:                  0.33
abstract:                 Download and summarize CPAN Testers data
author:
  - Barbie <barbie@cpan.org>
  - Leon Brocard <leon@astray.com>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Cwd:                              0
  Config::IniFiles:                 0
  CPAN::DistnameInfo:               0
  CPAN::Testers::Common::DBUtils:   0.03
  Class::Accessor::Fast:            0
  DBD::mysql:                       0
  DBD::SQLite:                      1.07
  Email::Simple:                    0
  File::Basename:                   0
  File::Path:                       0
  Getopt::Long:                     0
  MIME::Base64:                     0
  MIME::QuotedPrint:                0
  Net::NNTP:                        0
  version:                          0
recommends:
  Test::More:                       0.70
  Test::MockObject:                 0
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
  Test::CPAN::Meta:                 0.12
build_requires:
  Test::More:                       0.01

provides:
  CPAN::Testers::Data::Generator:
    file:     lib/CPAN/Testers/Data/Generator.pm
    version:  0.33
  CPAN::Testers::Data::Generator::Article:
    file:     lib/CPAN/Testers/Data/Generator/Article.pm
    version:  0.33

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Data-Generator

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
